platform :ios, '7.0'

target 'ImageFilterExample' do
  pod 'ImageFilters', :git => 'https://github.com/jameswomack/iOS-Image-Filters.git'
end

target 'ImageFilterExampleTests' do
  pod 'Specta'
  pod 'OCMockito'
end
